spring.application.name=student-management-system
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=i dont know

spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
